workflow

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -3,23 +3,23 @@ name: Build APK for React Native Android
 on:
   push:
     branches:
-      - main  # Set the branch you want to trigger the workflow
+      - main
   pull_request:
     branches:
-      - main  # Trigger when PRs are created to the main branch
+      - main
 
 jobs:
   build:
-    runs-on: ubuntu-latest  # The environment where the build will run (Linux, macOS, or Windows)
+    runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2  # Checkout the repository code
+        uses: actions/checkout@v2
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '16'  # Specify your Node.js version
+          node-version: '16'
 
       - name: Cache Node modules
         uses: actions/cache@v2
@@ -31,17 +31,24 @@ jobs:
 
       - name: Install dependencies
         run: |
-          npm install  # Or use yarn if you prefer
+          npm install
+
+      - name: Check for Android folder
+        run: |
+          if [ ! -d "android" ]; then
+            echo "Android folder not found. Did you forget to eject Expo?";
+            exit 1;
+          fi
 
       - name: Set up Android SDK
         run: |
           echo "sdk.dir=$HOME/Android/Sdk" > $GITHUB_WORKSPACE/android/local.properties
-          sudo apt-get install -y openjdk-11-jdk  # Install Java if needed
+          sudo apt-get install -y openjdk-11-jdk
 
       - name: Build APK
         run: |
           cd android
-          ./gradlew assembleRelease  # Build the APK in release mode
+          ./gradlew assembleRelease
 
       - name: Upload APK as artifact
         uses: actions/upload-artifact@v3
